const D={
risks:[["RSK-0042","Privileged account compromise","Identity",25,20,"IAM Manager","Treatment overdue"],["RSK-0038","Cloud storage exposure","Cloud",20,15,"Cloud Security","In treatment"],["RSK-0031","Unsupported server OS","Infrastructure",16,12,"Infrastructure","Open"],["RSK-0027","Third-party data breach","Vendor",15,10,"Third-Party Risk","Monitoring"]],
controls:[["ISO-A5.15","ISO 27001:2022","Access control",92,"Implemented"],["ISO-A5.23","ISO 27001:2022","Cloud services",78,"Partial"],["NIST-PR.AA","NIST CSF 2.0","Identity management",88,"Implemented"],["CIS-06","CIS Controls v8","Access control management",74,"Partial"],["PCI-08","PCI DSS 4.0.1","Authentication",71,"Partial"]],
evidence:[["EV-00124","MFA Access Review Q3.pdf","ISO-A5.15","IAM Team","Approved","2026-12-12"],["EV-00119","Cloud Configuration Baseline.xlsx","ISO-A5.23","Cloud Security","Pending","2026-10-02"],["EV-00115","PCI DSS Authentication Test.pdf","PCI-08","Compliance","Approved","2026-11-15"],["EV-00109","Vendor Security Assessment.docx","VRM-01","Third-Party Risk","Expired","2026-09-01"]],
incidents:[["INC-0264","Privileged login from unusual location","Critical","Investigating","SOC Team"],["INC-0261","Phishing campaign targeting finance users","High","Contained","Security Operations"],["INC-0258","Outdated TLS configuration detected","Medium","Open","Infrastructure"],["INC-0251","Cloud storage sharing misconfiguration","High","Resolved","Cloud Security"]],
assets:[["AST-0001","ERP Production","Application","Critical","IT","Production"],["AST-0018","Finance Database","Database","Critical","Data Team","Production"],["AST-0042","Azure Storage Account","Cloud","High","Cloud Team","Production"],["AST-0098","Staff Laptops","Endpoint","Medium","IT","Corporate"]],
vulns:[["CVE-2026-10021","Finance Database",9.1,"Critical","Open","2026-09-25"],["CVE-2026-08442","ERP Production",8.4,"High","In Remediation","2026-10-02"],["CVE-2026-07310","Staff Laptops",6.8,"Medium","Scheduled","2026-10-12"]],
vendors:[["VEN-001","Cloud Services Provider","Critical",82,"Assessment Due"],["VEN-002","Payroll SaaS","High",91,"Approved"],["VEN-003","Managed Network Services","High",74,"Remediation"]]
};
const nav=[["dashboard","Command Center"],["risks","Risk Management"],["controls","Control Library"],["evidence","Evidence"],["audits","Audit Management"],["incidents","Incident Management"],["assets","Asset Management"],["vulns","Vulnerability Management"],["vendors","Third-Party Risk"],["bcp","Business Continuity / DR"],["pci","PCI DSS 4.0.1"],["reports","Reports"],["settings","Settings"]];
const $=s=>document.querySelector(s), esc=x=>String(x??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let page=location.hash.slice(1)||"dashboard", query="";
const badge=(x,c="")=>`<span class="badge ${c||x.toLowerCase().replaceAll(" ","-")}">${esc(x)}</span>`;
const metric=(a,b,c)=>`<div class="metric"><small>${a}</small><strong>${b}</strong><span>${c}</span></div>`;
function shell(){return `<aside><div class="brand"><b>CT</b><div><strong>CyberTech 360</strong><small>Enterprise GRC</small></div></div><nav>${nav.map((n,i)=>`<button data-page="${n[0]}" class="${page===n[0]?"active":""}">${["◫","◇","◈","▣","▤","⚠","⌁","△","◉","↻","▦","▥","⚙"][i]} <span>${n[1]}</span></button>`).join("")}</nav><footer><i></i> Demo environment<small>Backend not configured</small></footer></aside><main><header><button id="menu">☰</button><div class="search">⌕<input id="q" placeholder="Search risks, controls, incidents, evidence…"><kbd>Ctrl K</kbd></div><button id="theme">☼</button><button id="copilot">✦ AI</button><div class="profile"><b>RS</b><span>Richmond Sarpong<small>Super Administrator</small></span></div></header><section id="content"></section></main>`}
function head(t,s,a=""){return `<div class="head"><div><em>CYBERTECH 360</em><h1>${t}</h1><p>${s}</p></div><div class="actions">${a}</div></div>`}
function table(h,rows){return `<div class="scroll"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.join(""):`<tr><td colspan="${h.length}" class="empty">No records found</td></tr>`}</tbody></table></div>`}
function btn(t,c="secondary",act=""){return `<button class="btn ${c}" ${act}>${t}</button>`}
function dashboard(){return head("Security Command Center","Executive posture across governance, risk, compliance and security operations.",btn("Export CSV","secondary","data-export='risks'")+btn("+ New Incident","primary","data-add='incident'"))+`<div class="metrics">${metric("Security posture","87/100","▲ 4.2%")}${metric("Open incidents",D.incidents.filter(x=>x[3]!=="Resolved").length,"▼ 12%")}${metric("Critical risks","2","1 overdue treatment")}${metric("Compliance","82%","▲ 3.1%")}${metric("Assets","1,248","▲ 38")}${metric("MTTD","18m","Target < 30m")}</div><div class="grid two"><article class="card"><h3>Security events trend <small>demo telemetry</small></h3><div class="chart">${[42,55,48,70,65,84,72,91,88,103,96,118].map(v=>`<i style="height:${v/1.4}px"></i>`).join("")}</div></article><article class="card"><h3>Framework posture</h3>${[["ISO 27001",88],["NIST CSF 2.0",84],["CIS Controls",79],["PCI DSS 4.0.1",72]].map(x=>`<div class="bar"><label>${x[0]}<b>${x[1]}%</b></label><span><i style="width:${x[1]}%"></i></span></div>`).join("")}</article></div><div class="grid three"><article class="card"><h3>Top risks</h3>${D.risks.map(r=>`<div class="row"><span><b>${r[0]}</b><small>${r[1]}</small></span>${badge(r[4],"risk")}</div>`).join("")}</article><article class="card"><h3>Recent incidents</h3>${D.incidents.map(r=>`<div class="row"><span><b>${r[1]}</b><small>${r[3]}</small></span>${badge(r[2])}</div>`).join("")}</article><article class="card"><h3>Control effectiveness</h3>${D.controls.map(r=>`<div class="bar"><label>${r[0]}<b>${r[3]}%</b></label><span><i style="width:${r[3]}%"></i></span></div>`).join("")}</article></div>`}
function pageView(){const map={risks:["Risk Management","Identify, assess, treat and monitor enterprise risks.",["ID","Risk","Category","Inherent","Residual","Owner","Status"],D.risks.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${badge(r[4],"risk")}</td><td>${r[5]}</td><td>${badge(r[6])}</td></tr>`)],"risk"},controls:["Control Library","Framework controls and implementation effectiveness.",["Control","Framework","Requirement","Score","Status"],D.controls.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}%</td><td>${badge(r[4],r[4]==="Implemented"?"ok":"warn")}</td></tr>`),"control"],evidence:["Evidence Management","Evidence ownership, control mapping, review and approval.",["Evidence","Control","Owner","Status","Review"],D.evidence.map(r=>`<tr><td><b>${r[0]}</b><br>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${badge(r[4],r[4]==="Approved"?"ok":r[4]==="Expired"?"Critical":"warn")}</td><td>${r[5]}</td></tr>`),"evidence"],incidents:["Incident Management","Detection through containment, recovery and lessons learned.",["ID","Incident","Severity","Status","Owner"],D.incidents.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${badge(r[2])}</td><td>${badge(r[3])}</td><td>${r[4]}</td></tr>`),"incident"],assets:["Asset Management","Authoritative inventory of technology and cloud assets.",["Asset","Type","Criticality","Owner","Environment"],D.assets.map(r=>`<tr><td><b>${r[0]}</b><br>${r[1]}</td><td>${r[2]}</td><td>${badge(r[3])}</td><td>${r[4]}</td><td>${r[5]}</td></tr>`),"asset"],vulns:["Vulnerability Management","CVE, CVSS, SLA and remediation tracking.",["CVE","Asset","CVSS","Severity","Status","Due"],D.vulns.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${badge(r[3])}</td><td>${badge(r[4])}</td><td>${r[5]}</td></tr>`),"vulnerability"],vendors:["Third-Party Risk","Supplier security assessment and remediation.",["ID","Vendor","Tier","Score","Status"],D.vendors.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${badge(r[2])}</td><td>${r[3]}</td><td>${badge(r[4])}</td></tr>`),"vendor"]}[page];
if(!map)return special();
return head(map[0],map[1],btn("Export CSV","secondary","data-export='"+page+"'")+btn("+ Add Record","primary","data-add='"+map[5]+"'"))+`<article class="card">${table(map[2],map[3])}</article>`}
function special(){const titles={audits:["Audit Management","Audit plans, evidence requests, findings and corrective actions."],bcp:["Business Continuity / DR","BIA, RTO/RPO, recovery strategy and exercise readiness."],pci:["PCI DSS 4.0.1","Merchant scope, CDE flow, requirements, evidence and remediation."],reports:["Reports","Management-ready security, risk, compliance and audit reporting."],settings:["Settings","Identity, tenant, integrations, frameworks and security configuration."]};const t=titles[page]||titles.audits;if(page==="pci")return head(t[0],t[1],btn("Export","secondary","data-export='pci'")+btn("+ Scope Item","primary","data-add='pci'"))+`<div class="metrics">${metric("PCI readiness","72%","Mapped demo controls")}${metric("Requirements","8/12","Assessed")}${metric("Evidence coverage","68%","Pending review")}${metric("High findings","3","Remediation")}</div><div class="grid two"><article class="card"><h3>Cardholder Data Flow</h3><div class="flow"><b>Customer</b> → <b>Payment Page</b> → <b>Gateway</b> → <b>Acquirer</b></div><p>Demo flow only. Replace with validated merchant-specific CDE documentation.</p></article><article class="card"><h3>Priority requirements</h3>${[["Req. 8",71],["Req. 10",84],["Req. 11",66],["Req. 12",78]].map(x=>`<div class="bar"><label>${x[0]}<b>${x[1]}%</b></label><span><i style="width:${x[1]}%"></i></span></div>`).join("")}</article></div>`;
if(page==="settings")return head(t[0],t[1])+`<div class="grid two"><article class="card"><h3>Identity & Access</h3><p>MFA: Required</p><p>RBAC: Enabled</p><p>SSO: Ready for configuration</p><p>Session timeout: 30 minutes</p></article><article class="card"><h3>Integrations</h3><p>Supabase: <b class="warn">Not configured</b></p><p>SIEM: Not connected</p><p>AI provider: Not configured</p></article><article class="card"><h3>Frameworks</h3><p>ISO 27001:2022 · Active</p><p>NIST CSF 2.0 · Active</p><p>CIS Controls v8 · Active</p><p>PCI DSS 4.0.1 · Active</p></article><article class="card"><h3>Production boundary</h3><p>This GitHub Pages build is demo mode. Configure Supabase, private storage, RLS and backend authorization before production use.</p></article></div>`;
return head(t[0],t[1],btn("Generate CSV","primary","data-export='reports'"))+`<div class="grid three">${["Executive Security Report","Enterprise Risk Report","ISO 27001 Assessment","PCI DSS Readiness Report","Incident Report","Vulnerability SLA Report"].map(x=>`<article class="card"><h3>${x}</h3><p>Generate from platform records after backend connection.</p>${btn("Generate","secondary","data-report='"+x+"'")}</article>`).join("")}</div>`}
function render(){document.body.className=localStorage.getItem("ct360_theme")==="light"?"light":"";document.getElementById("app").innerHTML=shell();const c=$("#content");c.innerHTML=page==="dashboard"?dashboard():pageView();bind()}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;location.hash=page;render()});$("#q").value=query;$("#q").oninput=e=>{query=e.target.value.toLowerCase();if(query)search(query);else render()};$("#theme").onclick=()=>{localStorage.setItem("ct360_theme",document.body.classList.contains("light")?"dark":"light");render()};$("#copilot").onclick=()=>alert("AI GRC Copilot is production-ready in the architecture, but no external AI key is configured in this public demo.");$("#menu").onclick=()=>document.querySelector("aside").classList.toggle("open");document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportCsv(b.dataset.export));document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelectorAll("[data-report]").forEach(b=>b.onclick=()=>alert(b.dataset.report+" queued for the production reporting worker."))}
function search(q){const hits=[];Object.entries(D).forEach(([k,a])=>a.forEach(x=>JSON.stringify(x).toLowerCase().includes(q)&&hits.push([k,x])));$("#content").innerHTML=head("Search Results","Global search across demo GRC records.")+`<article class="card">${table(["Module","ID","Record"],hits.map(h=>`<tr><td>${h[0]}</td><td><b>${esc(h[1][0])}</b></td><td>${esc(h[1][1]||"")}</td></tr>`))}</article>`;bind()}
function exportCsv(type){const a=D[type]||D.risks;const csv=a.map(r=>r.map(v=>JSON.stringify(v??"")).join(",")).join("\n");const x=document.createElement("a");x.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));x.download="cybertech360-"+type+".csv";x.click();URL.revokeObjectURL(x.href)}
function add(type){const name=prompt("Enter a short name for the new "+type+" record:");if(name)alert("Saved in demo mode: "+name+" — connect the production API for shared persistence.")}
render();